version: "3.8"
services:
  database:
    image: postgres:15-alpine
    restart: always
    hostname: $POSTGRES_HOST
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: