basePath: /
host: localhost:8080
info:
  contact:
    email: artem.lisitsynn@gmail.com
    name: Artem Lisitsyn
  description: This service is a task for the Avito internship. Provides you a REST
    API to work with user balances (crediting funds, debiting funds, transferring
    funds from user to user, as well as a method for obtaining a user's balance).
  title: Balance Managing service
  version: "1.0"
paths: {}
swagger: "2.0"
